### ISSUE TITLE
Replace Aux HOC with Fragments?

### ISSUE THREAD

**Issue by camjw** [T-Miller0/ecommerce-react#1]
I saw you've been using `<Aux>...</Aux>` to wrap a lot of suff where you don't want to use a div in a lot of these react repos. React introduced Fragments fairly recently which do the same thing and are built in (so you don't have to have a HOC for it). There's some documentation here: https://reactjs.org/docs/fragments.html.

Maybe you could use these instead?

The syntax is either:

```
import React, { Fragment } from 'react';

const FragmentedComponents = () => (
    <Fragment>
        <h3>This is in a fragment</h3>
        <h2>So is this</h2>
    </Fragment>
)
```

Or, you can replace the `<Fragment>` tag with just `<>` and `</>`, but I think some linters complain about those.

**Comment by T-Miller0** [comment]
Thanks Cam, I'll have a read and make changes. Appreciate the feedback
